local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

r2:
  service: S3
  endpoint: <%= ENV['R2_ENDPOINT'] %>
  access_key_id: <%= ENV['R2_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['R2_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['R2_BUCKET'] %>
  region: auto
  use_accelerate_endpoint: false
  force_path_style: true